config:
  aws:region: us-east-1
  nomad-dev-aws:sshPublicKeyPath: ~/.ssh/nomad-dev.pub
  nomad-dev-aws:instanceType: t3.micro
  nomad-dev-aws:enablePublicSsh: false
  nomad-dev-aws:enableMosh: false
  nomad-dev-aws:enableTailscaleUdp: false
